[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'cd backend && npm ci --production',
  'cd frontend && npm ci'
]

[phases.build]
cmds = ['cd frontend && npm run build']

[start]
cmd = 'cd backend && npm start'
